# Generated by Django 3.0.6 on 2021-01-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dinnersNote',
            field=models.CharField(default='default', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='note',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='Pictures'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
